version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - "8082:80"
    environment:
      - PUID=1002
      - PGID=1002
    volumes:
      - ./data:/srv
      - ./config/filebrowser.db:/database/filebrowser.db
      - ./config/settings.json:/config/settings.json
    restart: unless-stopped
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
