version: '3.8'

services:
  keeweb:
    image: antelle/keeweb:1.18.7
    container_name: keeweb
    ports:
      - "8180:443"
      - "8083:80"
    volumes:
      - ./databases/databases:/web/databases
      - ./config:/etc/nginx/external/
    restart: unless-stopped
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true

