version: '3.8'  

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:443"
      - "80:80"
      - "433:433"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    restart: unless-stopped
    networks:
      - network
#  Docker Compose automatically creates a network prefixed with the project name
# creates a network
networks:
  network:
    driver: bridge 
